<h2>Remove Content</h2>

<p>Are you sure you wish to remove this content from the system?</p>
<a data-role="button" data-theme="a" data-icon="check" href="/cms/content/remove/id/<?php echo $this->content->id; ?>" title="Yes remove content">Yes</a>
<a data-role="button" data-theme="a" href="/cms/content/manage/type/<?php echo $this->content->content_type; ?>" data-icon="delete" title="No, do not remove">No</a>