<h2>Content Fields: <?php echo $this->dataType['name']; ?></h2>
<p><a href="/cms/datatypefields/add/content-type/<?php echo $this->dataType['id']; ?>" data-role="button" data-theme="a" data-icon="plus">Add Content Field</a></p>

<!-- This is the table that contains all the content type fields in the system -->
<table >
    <thead>
        <th>Field Name</th>
        <th>Type</th>
        <th style="text-align:center;">Edit</th>
        <th style="text-align:center;">Remove</th>
    </thead>
    
    <tbody>
        <!--display all of the users and the links to edit the buggers-->
        <?php $i = 0; ?>
        <?php if ($this->dataTypeFields) : ?>
            <?php foreach($this->dataTypeFields as $field): ?>
                <tr <?php echo ($i %2 ) ? 'class="odd"' : ''; ?> >
                    <td><?php echo $field->name; ?></td>
                    <td><?php echo $field->format; ?></td>
                    <td class="center"><a data-role="button" data-theme="a" data-iconpos="notext" data-icon="gear" href="/cms/datatypefields/edit/id/<?php echo $field->id; ?>/content-type/<?php echo $this->dataType['id']; ?>" title="Edit <?php echo $field->name; ?>">Edit</a></td>
                    <td class="center"><a data-role="button" data-theme="a" data-iconpos="notext" data-rel="dialog" data-icon="delete" id="<?php echo $dataType['name']; ?>" href="/cms/datatypefields/remove-confirm/id/<?php echo $field->id; ?>/content-type/<?php echo $this->dataType['id'];?>" title="Remove <?php echo $field->name; ?>">Remove</a></td>
                </tr>
                <?php $i ++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
    
    
    
</table>

    

