<html>
    <body>
        
        <table cellpadding="0" cellspacing="0">
            
            <tr><td>Dear <?php echo $this->name; ?>,</td></tr>
            <tr><td>Your account has been deactivated due to you requesting a your user details.</td></tr>
            <tr><td>Your username is <strong><?php echo $this->username; ?></strong></td></tr>
            <tr><td>To activate your account again click the link bellow to change your password</td></tr>
            <tr><td><a href="<?php echo $this->passwordLink; ?>" title="Click here to activate new password"><?php echo $this->passwordLink; ?></a></td></tr>
            
        </table>
        
    </body>
    
</html>