
<h2>Manage Users</h2>
<p><a href="/user/add" data-role="button" data-theme="d" data-icon="plus">Add User</a></p>

<!-- This is the table that contains all the users in the system -->
<table>
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th style="text-align:center;">Edit</th>
        <th style="text-align:center;">Remove</th>
    </thead>
    
    <tbody>
        <!--display all of the users and the links to edit the buggers-->
        <?php $i = 0; ?>
        <?php foreach($this->users as $user): ?>
            <tr <?php echo ($i %2 ) ? 'class="odd"' : ''; ?> >
                
                <td><?php echo $user->first_name; ?></td>
                <td><?php echo $user->last_name; ?></td>
                
                <td style="width:10%;"><a data-role="button" data-theme="b" data-icon="gear" href="/user/edit/id/<?php echo $user->id; ?>" title="Edit <?php echo $user->first_name .' '. $user->last_name; ?>">Edit</a></td>
                <td style="width:10%;"><a data-role="button" data-theme="b" data-rel="dialog" data-icon="minus" id="<?php echo $user->id; ?>" href="/user/remove-confirm/id/<?php echo $user->id; ?>" title="Remove <?php echo $user->first_name .' '. $user->last_name; ?>">Remove</a></td>
            </tr>
            <?php $i ++; ?>
        <?php endforeach; ?>
    </tbody>
    
    
    
</table>
