<h2>Content Types</h2>
<p><a href="/cms/datatypes/add" data-role="button" data-theme="a" data-icon="plus">Add Content Type</a></p>

<!-- This is the table that contains all the users in the system -->
<table >
    <thead>
        <th>Content Type</th>
        <th style="text-align:center;">Rename</th>
        <th style="text-align:center;">Fields</th>
        <th style="text-align:center;">Remove</th>
    </thead>
    
    <tbody>
        <!--display all of the users and the links to edit the buggers-->
        <?php $i = 0; ?>
        <?php foreach($this->dataTypes as $dataType): ?>
            <tr <?php echo ($i %2 ) ? 'class="odd"' : ''; ?> >
                <td><?php echo $dataType->name; ?></td>
                <td class="center"><a data-role="button" data-theme="a" data-icon="gear" data-iconpos="notext" href="/cms/datatypes/edit/id/<?php echo $dataType->id; ?>" title="Rename <?php echo $dataType->name; ?>"></a></td>
                <td class="center"><a data-role="button" data-theme="a" data-icon="gear" data-iconpos="notext" href="/cms/datatypefields/index/id/<?php echo $dataType->id; ?>" title="Edit Fields"></a></td>
                <td class="center"><a data-role="button" data-theme="a" data-rel="dialog" data-iconpos="notext" data-icon="delete" id="<?php echo $dataType->name; ?>" href="/cms/datatypes/remove-confirm/id/<?php echo $dataType->id; ?>" title="Remove <?php echo $dataType->name; ?>"></a></td>
            </tr>
            <?php $i ++; ?>
        <?php endforeach; ?>
    </tbody>
    
    
    
</table>

    

