CREATE TABLE `templates` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    `name` VARCHAR( 500 ) NOT NULL ,
    `file` VARCHAR( 500 ) NOT NULL ,
    `content_types` VARCHAR( 1000 ) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=3;

--//@UNDO

DROP TABLE `templates`;

--//