<html>

<head>
    <meta charset="utf-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php 
        $this->headLink()->appendStylesheet('http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css')
                         ->appendStylesheet('/cms/assets/css/mobile/jiggly.min.css')
                         ->appendStylesheet("/cms/assets/css/style.css")
                         ->appendStylesheet("/cms/assets/css/desktop/desktop.css");

        $this->headScript()->appendFile('/cms/assets/js/libs/jquery-1.6.2.min.js')
                           ->appendFile("http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js");
        
        $this->headScript()->appendFile('/cms/assets/js/libs/global.js');
        $this->headScript()->appendFile('/cms/assets/js/desktop/script.js');
    ?>
    
    <!--[if lt IE 7 ]>
        <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
        <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
    
    <!--[if lt IE 9]>
        <?php $this->headScript()->appendFile('/cms/assets/js/libs/html5shiv.js'); ?>>
    <![endif]-->
        
    <?php
        echo $this->headLink();
        echo $this->headScript();
    ?>
    
    <meta name="description" content="Jiggly CMS, content management for the people!">
    <meta name="author" content="Gareth Fuller">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
</head>
<body>
    <?php echo $this->render('dialog-header.phtml') ?>
 

    <div id="content" data-role="content" data-theme="a">
        
        <?php if (isset($this->messages[0]) && ($this->messages[0] != '')): ?>
            
            <div class="ui-state-highlight ui-corner-all"> 
                    <p><span class="ui-icon ui-icon-info"></span>
                    <?php echo $this->messages[0]; ?></p>
            </div>
   
            <div class="clear-both"></div>
        <?php endif ?>
        
        <?php echo $this->layout()->content; ?>
    </div>
    
    <div class="clear-both"></div>
    <?php echo $this->render('footer.phtml') ?>
</body>
