<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php 
         $this->headLink()->prependStylesheet('/cms/assets/css/mobile/jiggly.min.css')
                         ->prependStylesheet('http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css')
                         ->prependStylesheet("/cms/assets/css/mobile/style.css");
        echo $this->headLink();
        $this->headScript()->prependFile("/cms/assets/js/script.js")
                           ->prependFile("http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js")
                           ->prependFile("/cms/assets/js/libs/jquery-1.6.2.min.js")
                           ->prependFile("/cms/assets/js/libs/modernizr-2.0.6.min.js");
        echo $this->headScript();
    ?>
    
    <!--[if lt IE 7 ]>
        <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
        <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
    
    <meta name="description" content="Jiggly CMS, content management for the people!">
    <meta name="author" content="Gareth Fuller">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
</head>
<body>
    <?php echo $this->render('dialog-header-mobile.phtml') ?>
 

    <div id="content" data-role="content" data-theme="a">
        
        <?php if (isset($this->messages[0]) && ($this->messages[0] != '')): ?>
            
            <div class="ui-state-highlight ui-corner-all"> 
                    <p><span class="ui-icon ui-icon-info"></span>
                    <?php echo $this->messages[0]; ?></p>
            </div>
   
            <div class="clear-both"></div>
        <?php endif ?>
        
        <?php echo $this->layout()->content; ?>
    </div>
    
    <div class="clear-both"></div>
    <?php echo $this->render('footer-mobile.phtml') ?>
</body>
