<?php
$auth = Zend_Auth::getInstance();

if ($auth->hasIdentity()){
    $identity = $auth->getIdentity();
} 

?>
<header data-role="header" data-add-back-btn="true" id="header">
    
    <div id="no-markup">
    <a href="/cms" id="mobile-logo">Jiggly CMS</a>
    </div>
    <?php 
    if (isset($identity)){
        
        $navForm = new Application_Form_MobileNavForm();
        
        if ($identity->role == 'admin' || $identity->role == 'superadmin'){
            $navForm->getElement('nav')->addMultiOption('user', 'Users');
            $navForm->getElement('nav')->addMultiOption('api', 'Api Users');
        }
        
        if ($identity->role == 'superadmin'){
            $navForm->getElement('nav')->addMultiOption('datatypes', 'Content Types');
        }
        
        // Need an instance of the controller to get acces to this
        $controller = Zend_Controller_Front::getInstance();
        
        $navForm->getElement('nav')->addMultiOption('logout', 'Logout');
        $navForm->getElement('nav')->setValue($controller->getRequest()->getControllerName());
  

        // Set decorators for form elements
        $decorators = array(
                'ViewHelper',
                'Description',
                'Errors',
                array(array('Input' => 'HtmlTag'), array('tag' => 'dd')));
        
        $navForm->setElementDecorators($decorators);
        

        // Handle the form post
        if ($controller->getRequest()->isPost()){
            if ($navForm->isValid($_POST)) {
                
                $formValues = $navForm->getValues();
                $redirect = '';
                
                switch ($formValues['nav']){
                    case 'index':
                        $redirect = '/cms/';
                        break;
                    case 'content':
                        $redirect = '/cms/content';
                        break;
                    case 'datatypes':
                        $redirect = '/cms/datatypes';
                        break;
                    case 'user':
                        $redirect = '/cms/user';
                        break;
                    case 'api':
                        $redirect = '/cms/api';
                        break;
                    case 'logout':
                        $redirect = '/cms/user/logout';
                        break;
                    default:
                        $redirect = '/cms/home';
                        break;
                }
                
                // Do the redirect to the correct page
                header('Location: '.$redirect);
                return;
                
            }
        
        }
        
        echo $navForm;
    } 
    ?>
    
  
</header>