<?php $auth = Zend_Auth::getInstance(); ?>
<?php if ($auth->hasIdentity()): ?>
<?php $identity = $auth->getIdentity(); ;?>
<?php endif; ?>
<header data-role="header" data-add-back-btn="true">
    <?php /*<h1><?php if($this->pageTitle){echo $this->pageTitle;}else{echo '<a href="/cms" >Jiggly CMS</a>';}?></h1>
    <?php if ($auth->hasIdentity()): ?>
    <?php $identity = $auth->getIdentity(); ;?>
    <div id="right-side">
        <p>Hello again: <?php echo $identity->first_name .' '. $identity->last_name; ?></p>
        <a data-role="button" data-theme="a" href="/cms/logout" title="Logout">Logout</a>
    </div> */?>
    <div id="left-side">
        <nav>
            <a data-role="button" data-icon="home" title="Home" data-theme="a" href="/cms">Home</a>
            <a data-role="button" data-theme="a" data-icon="plus" title="Add Content" href="/cms/content">Add Content</a>
            <?php if ($identity): ?>
                <a data-role="button" data-theme="a" href="/cms/logout" title="Logout">Logout</a>
            <?php endif; ?>
            <?php if ($identity->role == 'admin'): ?>
                <a data-role="button" data-theme="a" data-icon="gear" title="Manage Users" href="/cms/user/manage">Manage Users</a>
                <a data-role="button" data-theme="a" data-icon="gear" title="Site Settings" href="/cms/settings">Site Settings</a>
                <a data-role="button" data-theme="a" data-icon="gear" title="API Users" href="/cms/api/manage">API Users</a>
            <?php endif; ?>
           
        </nav>
    </div>
    
    

</header>