<?php
$auth = Zend_Auth::getInstance();

if ($auth->hasIdentity()){
    $identity = $auth->getIdentity();
} 
?>
<header data-role="header" data-add-back-btn="true" id="header">
    
    <?php if (isset($identity)): ?>
    <nav id="nav-wrapper">
        <a data-role="button" data-icon="home" title="Home" data-theme="a" href="/cms">Home</a>
        <a data-role="button" data-theme="a" data-icon="plus" title="Add Content" href="/cms/content">Content</a>


        <?php if ($identity->role == 'admin' || $identity->role == 'superadmin'): ?>
            <a data-role="button" data-theme="a" data-icon="gear" title="Manage Users" href="/cms/user/manage">Manage Users</a>
            <a data-role="button" data-theme="a" data-icon="gear" title="API Users" href="/cms/api/manage">API Users</a>
        <?php endif; ?>
            
        <?php if ($identity->role == 'superadmin') :?>
            <a data-role="button" data-theme="a" data-icon="gear" title="Content Types" href="/cms/contenttypes">Content Types</a>
            <a data-role="button" data-theme="a" data-icon="gear" title="Templates" href="/cms/templates">Templates</a>
        <?php endif; ?>

        <a data-role="button" data-theme="a" href="/cms/logout" title="Logout">Logout</a>

    </nav>
    <?php endif; ?>
    

</header>