<h2>Remove Template</h2>

<p>Are you sure you wish to remove template <?php echo $this->template->name; ?> from the system?</p>
<p>!!!! Note, removing this template from the system will make all content using this template unassigned !!!!</p>
<a data-role="button" data-theme="a" data-icon="check" href="/cms/template/remove/id/<?php echo $this->template->id; ?>" title="Yes remove template">Yes</a>
<a data-role="button" data-theme="a" href="/cms/template/" data-icon="delete" title="No, do not remove">No</a>