<div id="center-container">
    
    <h2>Add Content Field: <?php echo $this->dataType['name']; ?></h2>
    <p>Use the form below to add a content type field to the system.</p>
    
    
    
    <?php echo $this->contentTypeFieldForm; ?>
    
    <div class="clear-both"></div>
    
    <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="back" title="Back">Back</a>
    
</div>