
<?php if (isset($this->content)) : ?>

    <div id="left-content-col">
        <h3>Current Content</h3>
        <?php foreach($this->content as $type => $contentItem): ?>

            <ul class="content-type-container">
                <li><a href="/cms/index/filter/<?php echo $contentItem->id; ?>" id="content-select-<?php echo $type; ?>" title="<?php echo ucfirst($type); ?>"><?php echo ucfirst($type); ?></a></li>
            </ul>

        <?php endforeach; ?>
    </div>

    <div id="center-container-home">


        <!-- this is the where the pages are going to go -->


    </div>

    <div id="bottom-container-home">
        
        <!-- at this point there is nothing in this section as there is no filter set -->
        <?php foreach($this->content as $type => $contentItem): ?>
            <ul>
            <?php
            if (isset($contentItem[0])):
                foreach($contentItem[0] as $item):
                    ?>

                    <li>
                        <h4><?php echo $item->ref; ?></h4>
                        <a href="/cms/content/edit/id/<?php echo $item->id; ?>" title="Edit">Edit</a>
                        <a href="/cms/content/remove-confirm/id/<?php echo $item->id;?>" title="Remove">Remove</a> 
                    </li>

                    <?php 
                endforeach;
            endif;?>
            </ul>
        <?php
        endforeach;
        ?>
        
    </div>

        
<?php endif; ?>

