<?php $auth = Zend_Auth::getInstance(); ?>
<?php if ($auth->hasIdentity()): ?>
<?php $identity = $auth->getIdentity(); ;?>
<?php endif; ?>

<a data-role="button" data-theme="a" data-icon="plus" title="Add Content" href="/cms/content">Add Content</a>

<?php if ($identity->role == 'admin' || $identity->role == 'superadmin'): ?>
    <a data-role="button" data-theme="a" data-icon="gear" title="Manage Users" href="/cms/user/manage">Manage Users</a>
<?php endif; ?>

    

