<?php
// Show all the ocntent in the system first
?>

<h2>Willkommen!, marvel at the current content!</h2>
<?php if (isset($this->content)) : ?>
<ul>
<?php foreach($this->content as $type => $contentItem){ ?>
    <li><?php echo ucfirst($type); ?></li>
    <li><ul>
            <?php
            $contentData = unserialize($contentItem[0]->content);
            foreach ($contentData as $key => $val){
            ?>
            <li><?php echo ucfirst($key) .': '.$val[0]; ?></li>
            <?php }; ?>
        </ul></li>

<?php }; ?>
<ul>
<?php endif; ?>
