<?php $auth = Zend_Auth::getInstance(); ?>
<header data-role="header">
    <?php if ($auth->hasIdentity()): ?>
    <?php $identity = $auth->getIdentity(); ;?>
    <div id="left-side">
        Hello again: <?php echo $identity->first_name .' '. $identity->last_name; ?>
    </div>
    <div id=""right-side">
        <nav>
            <a class="button" data-role="button" href="/logout">Logout</a>
            <?php if ($identity->role == 'admin'): ?>
                <a class="button" data-role="button" href="/user/manage">Manage Users</a>
            <?php endif; ?>
        </nav>
    </div>
    <?php endif; ?>

</header>