<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php 
        echo $this->headTitle();
        $this->headLink()->prependStylesheet("/assets/css/style.css")
                         ->prependStylesheet('/assets/css/custom-theme/jquery-ui-1.8.18.custom.css'); 
        echo $this->headLink();
        $this->headScript()->prependFile("/assets/js/script.js")
                           ->prependFile("/assets/js/libs/jquery-ui-1.8.18.custom.min.js")
                           ->prependFile("/assets/js/libs/jquery-1.6.2.min.js")
                           ->prependFile("/assets/js/libs/modernizr-2.0.6.min.js")
                           ->prependFile("/assets/js/mylibs/Bauhaus_93_400.font.js")
                           ->prependFile("/assets/js/mylibs/cufon.js");
        echo $this->headScript();
    ?>
    
    <!--[if lt IE 7 ]>
        <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
        <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
    
    <script type="text/javascript">
            Cufon.replace('h1');
            Cufon.replace('h2');
    </script>
    
    <meta name="description" content="Jiggly CMS, content management for the people!">
    <meta name="author" content="Gareth Fuller">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
</head>
<body>
    <h1><a href="/" >Jiggly CMS</a></h1>
    
    <?php echo $this->render('header.phtml') ?>
 

    <div id="content">
        
        <?php if (isset($this->messages[0]) && ($this->messages[0] != '')): ?>
            
            <div class="ui-state-highlight ui-corner-all"> 
                    <p><span class="ui-icon ui-icon-info"></span>
                    <?php echo $this->messages[0]; ?></p>
            </div>
   
            <div class="clear-both"></div>
        <?php endif ?>
        
        <?php echo $this->layout()->content; ?>
    </div>
    
    <div class="clear-both"></div>
    <?php echo $this->render('footer.phtml') ?>
</body>
