<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
</head>
<body>
    <h1>Jiggly CMS</h1>
    
    <?php echo $this->render('header.phtml') ?>
 

    <div id="content">
        
        <?php if (isset($this->messages[0]) && ($this->messages[0] != '')): ?>
            <div class="flash-messages">
                <?php echo $this->messages[0]; ?>
            </div>
        <?php endif ?>
        
        <?php echo $this->layout()->content; ?>
    </div>
 
    <?php echo $this->render('footer.phtml') ?>
</body>
</html>