<h1>Jiggly CMS</h1>


<?php 

// Login\out controlls and welcome message

$auth = Zend_Auth::getInstance();
$loggedIn = false;
if ($auth->hasIdentity()) {
    // Identity exists; get it
    $identity = $auth->getIdentity();
    
    //Zend_Debug::dump($identity);
    //exit();
    
    $loggedIn = true;
}
        
if (!$loggedIn): ?>
    <a href="/login">Login</a>
<?php else: ?>
    <h3>Hello again: <?php echo $identity->first_name .' '. $identity->last_name; ?></h3>
    <a href="/logout">Logout</a>
<?php endif ?>


<?php if (isset($this->messages[0]) && ($this->messages[0] != '')): ?>
    <div class="flash-messages">
        <?php echo $this->messages[0]; ?>
    </div>
<?php endif ?>

<?php echo $this->layout()->content; ?>