<html>
    <body>
        
        <table cellpadding="0" cellspacing="0">
            
            <tr><td>Dear <?php echo $this->name; ?>,</td></tr>
            <tr><td>Your password has been reset please click on the following link to activate your new password</td></tr>
            <tr><td><a href="<?php echo $this->passwordLink; ?>" title="Click here to activate new password"><?php echo $this->passwordLink; ?></a></td></tr>
            
        </table>
        
    </body>
    
</html>